services:
  postgres:
    container_name: postgres-nestjs-drizzle
    image: postgres:13.15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres
 
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin-nestjs-drizzle
    image: dpage/pgadmin4:8.6
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
    depends_on:
      - postgres
 
networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: